spring:
  application:
    name: lovable-clone

  datasource:
    url: jdbc:postgresql://localhost:9000/lovabledb
    username: lovableUser
    password: lovablePassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: Asia/Kolkata

  ai:
    openai:
      api-key: #####PLACEHOLDER#####
      base-url: https://api.openai.com
      chat:
        options:
          model: gpt-4o-mini    # gpt-5.2-codex
          temperature: 0.0

logging:
  level:
    org.springframework.ai:
      chat.client: DEBUG

jwt:
  secret-key: #####PLACEHOLDER#####

stripe:
  api:
    secret: #####PLACEHOLDER#####
    publish: #####PLACEHOLDER#####
  webhook:
    secret: #####PLACEHOLDER#####

client.url: http://localhost:8080

openrouter:
  api-key: #####PLACEHOLDER#####