spring:
  application:
    name: lovable-clone

  datasource:
    url: jdbc:postgresql://localhost:9000/lovabledb
    username: lovableUser
    password: lovablePassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: Asia/Kolkata

server:
  servlet:
    context-path: /api/v1

jwt:
  secret-key: 8538509589utiogsfsuFJFHD8JHFR8545849058fshHFFH89fFS7548

stripe:
  api:
    secret: <..>
    publish: <..>
  webhook:
    secret: <..>

client.url: http://localhost:8080